### ISSUE TITLE
OIT

### ISSUE THREAD

**Issue by ED-97** [nvpro-samples/optix_advanced_samples#18]
in OPTIXglass example , you launch light repeatedly to get fragment,if i want to save this fragment in device memory how i should do,(dynamic application) because if i get a enough memory (i success to relize the way) this need to a bigger memory than i need do you have other way(i have tried to malloc in optix but the .cu file need to compile to .ptx file,optix don't allow me to do)

**Comment by droettger** [comment]
First of all, OIT algorithms are used in rasterizers and don't apply to a ray tracer which is by design handling transparency in the correct order. Means there is no need to store all transmission events along a ray path to calculate the correct transparency in a ray tracer.

If you still need that, then you'd need to allocate a big enough output buffer before your launch to be able to hold all potential results from a single launch and write your results into that inside the ray generation program. 
Depending on the result vector size, that might exceed your available VRAM amount in which case you could partition the work into smaller subsets, for example, by rendering the image in smaller tiles (with multiple launches).

If the number of results which need to be stored is different per launch index, it's also possible to implement a simple linked list inside an output buffer by using a global index variable (which needs to be in a buffer as well, since all output in OptiX goes through buffers!) which can be incremented with an atomic operation to be able to fetch a new list element for each thread running in parallel.
There would need to be room for one element per launch index as the start element of each linked list, and then additional memory for all following list elements.
An element in that could be as simple as (float3 result, int index_to_next_element). Index 0 would indicate the end of the list, negative indices could be used to indicate empty elements and out-of-memory events.
This allows storing differently sized result vectors per launch index instead. Caveats are that this could still run out of memory, which would need to be indicated inside the next list index, and the results need to be read by iterating over the list after the launch.

(That mechanism of building such list is actually used in some rasterizer OIT algorithms.
For more information about OIT inside a rasterizer, please have a look at this example which demonstrates seven different OIT algorithms using Vulkan: https://github.com/nvpro-samples/vk_order_independent_transparency)

Note that the optix_advanced_samples based on OptiX 5 are considered legacy and should not be used for new developments since there exists the OptiX 7 API which is more modern, explicit, and always faster than OptiX 1 - 6 versions.
Find more information about that here:
https://raytracing-docs.nvidia.com/
https://forums.developer.nvidia.com/c/gaming-and-visualization-technologies/visualization/optix/167

**Comment by ED-97** [comment]
yes i want get transparency in the correct order, i have try to the way of link list,but i have two problem:

**Comment by ED-97** [comment]
yes i want to get transparency in the correct order, i have try to the way of link list,but i have two problem:
1、i have to allocate a big memory . can i allocate a memory dynamically.
2、cuda's atomic can't guarantee my code correctly. in every frame i get the __device__ fragmentindex, i hava to set the variate to zero, but i now use if(optixGetLaunchIndex.x==0&&optixGetLaunchIndex.y==0)atomicExch(&fragmentindex,0u); i think this way may get error result ,though i have not come across.
do you have some way solve my problem

**Comment by droettger** [comment]
1.) You cannot allocate memory dynamically inside the OptiX device programs.
https://raytracing-docs.nvidia.com/optix6/guide_6_5/index.html#caveats#caveats
As explained you would need to allocate a big enough OptiX output buffer before your launch and then manage the access to that inside the OptiX device programs yourself.

2.) To build a linked list in CUDA you simply need an index to the next free element in some buffer which you get and increment in an atomic way with the call atomicAdd(&nextElementIndex, 1). That returns the old index which is your next free element, and increments the nextElementIndex by 1. 
That way you can call that from as many CUDA threads as you want and each gets a different unique value back.

Now since OptiX only allows that in buffers, you would need to hold that nextElementIndex inside a buffer. It either needs a buffer with just a single unsigned int or you could reserve the zeroth element inside the "overflow" buffer which holds all list elements except the first which needs to be held for each launch index as start of the list.
You initialize that nextElementIndex on the host, and that means it needs to be an INPUT_OUTPUT buffer in that old OptiX API. 
(Inside OptiX 7 "buffers" are native CUdeviceptr which makes such things a lot simpler.)

3.) When device memory is a concern, a completely different approach would be to implement this with multiple OptiX launch calls where each launch is shooting only the continuation ray. Means the output buffer would need to hold the next ray and your transparency result and then you launch that as often as you need. (Such algorithms are called "wavefront" renderers.)
Problem with that is that most launch indices will not have any work to do when they reached the miss program, so this could require sophisticated work gathering to be efficient.

I'm curious why you would need to be able to store all transmission event data along ray paths in a progressive Monte Carlo raytracer. This makes no sense for image synthesis with a raytracer because that handles transparency naturally. 
The "order independent" in OIT refers to the primitive raster order inside a rasterizer and that doesn't affect a ray tracer because that works on the whole scene.

**Comment by ED-97** [comment]
yes i allocate a nextelementindex buffer save the index of every pixel
i want to optional every pixel's opacity ,so i have to save fragment.( though optix may not be the best choice
thanks for your answer ,i think i have know how i should do.
