### ISSUE TITLE
Warning about DevIL

### ISSUE THREAD

**Issue by mahmoodn** [nvpro-samples/optix_advanced_samples#4]
Hi
I don't understand DevIL part of the build instructions. What should I install and the set the variables? 

```
 CMake Warning at optixIntroduction/CMakeLists.txt:41 (message):
   DevIL image library not found.  Please set IL_LIBRARIES, ILU_LIBRARIES,
   ILUT_LIBRARIES, and IL_INCLUDE_DIR to build OptiX introduction samples 07
   to 10.
```

**Comment by droettger** [comment]
When you open the top-most CMakeLists.txt and click Configure, this message appears because inside the OptiX Introduction examples 07 to 10 the DevIL library is used to load images into textures.

Please follow the "DevIL" link inside the OptiX Introduction README.md 
https://github.com/nvpro-samples/optix_advanced_samples/tree/master/src/optixIntroduction

There you click on downloads and find the "DevIL 1.8.0 SDK for Windows" link.
Download that and unzip it locally where you like to store SDKs under Windows.

Now inside the CMake GUI - because the standard CMake FindDevIL.cmake under Windows has no mechanism to find the DevIL libraries and includes automatically - you need to put in the proper 
locations of IL_LIBRARIES, ILU_LIBRARIES, ILUT_LIBRARIES, and IL_INCLUDE_DIR.

That could look like this:
IL_LIBRARIES        C:/sdk/DevIL/lib/x64/Release/DevIL.lib
ILU_LIBRARIES     C:/sdk/DevIL/lib/x64/Release/ILU.lib
ILUT_LIBRARIES   C:/sdk/DevIL/lib/x64/Release/ILUT.lib
IL_INCLUDE_DIR  C:/sdk/DevIL/include

Then press "Configure" again and that message should disappear and after "Generate" the optixIntor_07 to _10 projects should appear in your OptiX Advanced Samples solution.

**Comment by droettger** [comment]
If this is under Linux, you would need to install the respective DevIL SDK as well.
Though since Linux has stricter installation placements for application and SDKs, CMake's FindDevIL.cmake should be able to find the three libraries and the include directory automatically.
Otherwise you should still be able to put in the lib file locations and path to the includes manually.

**Comment by mahmoodn** [comment]
OK. I manually cloned DentonW/DevIL from github and built it using the default options in order to install it in the system folders. Now, it is fine. Thanks.
